### ISSUE TITLE
Sounds.json compatibility

### ISSUE THREAD

**Issue by googlescientificnameforapig** [magneticflux-/fabric-start-the-music#9]
On the 1.19 version, I have a texture pack that has a sounds.json file. The texture pack sounds from the music.game ID does not play or at least I have not heard it play after so many attempts of spamming the start and stop button. this only happens in survival mode. Occasionally I manage to get a sounds.json file sound, but thats just very rare. Idk if its this mod's problem or minecraft's problem. It might be minecraft but it also might be this mod. I did not have this problem in 1.18

**Comment by googlescientificnameforapig** [comment]
Its mostly just default music.

**Comment by magneticflux-** [comment]
A resourcepack can add music to the `music.game` event with a certain weight, which defaults to 1. There are already 16 entries in the vanilla list, so an additional music track would only be played once every 17 times on average. To test that the system is working properly, you could add a weight of some large number like 10000 to a known sound so it should almost always play.

This mod doesn't alter any of the music choices, it simply instructs the game that it is due to play another music track when the key is pressed.

**Comment by googlescientificnameforapig** [comment]
But somehow, my texture pack music plays way more often when I'm in creative mode and, I have about 31 soundtracks in my texture pack.

**Comment by magneticflux-** [comment]
In creative mode, the `music.creative` event is used which includes the `music.game` event, along with some creative-only tracks.

You can also try using the `replace` option to eliminate vanilla sounds.

The wiki has more info [here](https://minecraft.fandom.com/wiki/Sounds.json#File_structure).

Otherwise, I don't know how to help. The mod basically just does this: https://github.com/magneticflux-/fabric-start-the-music/blob/2eeb03c841631dbf81d3d81c77e09a58a4a9d6e0/src/main/java/com/skaggsm/startthemusic/FabricStartTheMusicClient.java#L34
so it shouldn't change anything relating to `sounds.json`.

**Comment by googlescientificnameforapig** [comment]
Thx increasing the weight fixed the problem
